version: 0.2

phases:
  install:
    commands:
    - echo Entering install phase...
    - pip install --upgrade awscli
  pre_build:
    commands:
    - echo Entering pre_build phase...
    - echo Testing...
    - mvn test
  build:
    commands:
    - echo Entering build phase...
    - echo Build started on `date`
    - mvn package
  post_build:
    commands:
    - echo Entering post_build phase...
    - echo Build completed on `date`
artifacts:
  files:
  - '**/*'
  base-directory: 'target/centralservice'



